Release code 201801021

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -1,24 +1,24 @@
 #!/sbin/sh
 # MC's Charging Controller (mcc)
 # mcc update-binary
-# versionCode = 201801011
+# versionCode = 201801021
 # MCMotherEffin' @ XDA Developers
 
 # Detect whether in boot mode
 
 if ! (ps | grep zygote | grep -qv grep); then
-  boot_mode=false
+  is_boot_mode=false
 
   if (ps -A 2>/dev/null | grep zygote | grep -qv grep); then
-    boot_mode=true; fi
+    is_boot_mode=true; fi
 else
-  boot_mode=true
+  is_boot_mode=true
 fi
 
 # Abort if recovery installation
 # ( kernel compatibility issues )
 
-if ! ($boot_mode); then
+if ! ($is_boot_mode); then
 
   output_fd=$2
   ui_print() {
@@ -45,17 +45,7 @@ image=      # image will be found and set later
 
 error() { echo -e "(!) $1\n"; exit 1; }
 
-get_prop() { sed -n s/^$1=//p $2; }
-
-set_prop() { sed -i "s|$1=.*|$1=$2|g" $mod_path/data/settings.conf; }
-
-is_mounted() { grep -q " $1 " /proc/mounts; }
-
 is_charging() { grep -q ^POWER_SUPPLY_STATUS=[Cc]harging$ $uevent; }
-
-imgsize_test() {
-  e2fsck -n $image | grep -Eo '[0-9]+/[0-9]+ blocks' | cut -d/ -f$1 | awk '{print int($1 / 256)}'
-}
 
 set_perms_recursive() {
   find $1 | while read entry; do
@@ -74,8 +64,8 @@ set_perms_recursive() {
 magisk_bb=$(find /data -type f -name busybox | grep /magisk/busybox$)
 
 if [ ! -x "$magisk_bb" ]; then
-  echo -e "(!) Could not find MAGISK internal BusyBox\n"
-  error 'Please install MAGISK v14.0+'
+  echo -e "(!) Could not find Magisk internal BusyBox\n"
+  error 'Please install Magisk v14.0+'
 fi
 
 for func in $($magisk_bb --list); do
@@ -94,7 +84,7 @@ else
   system=/system
 fi
 
-# Detect MAGISK mount point
+# Detect Magisk mount point
 
 for loop_device in /dev/block/loop*; do
 
@@ -116,7 +106,7 @@ done
 if [[ ! -z $mount_point ]]; then
   main_mod_path=$mount_point/mcc
 else
-  error 'Could not find MAGISK mount point'
+  error 'Could not find Magisk mount point'
 fi
 
 # Print module name
@@ -214,11 +204,15 @@ fi
 if [[ -f $image ]]; then
   echo -e "(i) $image detected\n"
 
+  imgsize_test() {
+    e2fsck -n $image | grep -Eo '[0-9]+/[0-9]+ blocks' | cut -d/ -f$1 | awk '{print int($1 / 256)}'
+  }
+
   img_used=$(imgsize_test 1)
   img_total=$(imgsize_test 2)
   img_free=$((img_total - img_used))
 
-  if [[ ! $img_free -gt 1 ]]; then
+  if [[ ! $img_free -gt 0 ]]; then
     imgsize_new=$(((img_used + 1) / 32 * 32 + 64))
     echo -e "(i) Resizing $image to ${imgsize_new}M...\n"
     resize2fs $image ${imgsize_new}M
@@ -243,12 +237,15 @@ for loop in 0 1 2 3 4 5 6 7; do
   if (losetup $loop_device $image); then
     mount -t ext4 -o loop $loop_device $mount_path; fi
 
-  if (is_mounted $mount_path); then break; fi
+  is_mounted() { grep -q " $mount_path " /proc/mounts; }
+  if (is_mounted); then break; fi
 done
-if ! (is_mounted $mount_path); then
+if ! (is_mounted); then
   error "Could not mount $image"; fi
 
 # Detect whether installed or not
+
+get_prop() { sed -n s/^$1=//p $2; }
 
 if [[ -f $mod_path/module.prop ]]; then
   cur_ver_code=$(get_prop versionCode $mod_path/module.prop)
@@ -262,7 +259,7 @@ fi
 
 # Detect whether to install / uninstall
 
-if [[ $cur_ver_code -ge 201801011 ]]; then
+if [[ $cur_ver_code -ge 201801021 ]]; then
 
   # Uninstall
 
@@ -302,6 +299,8 @@ else
 
   if [[ ! -z $set_1 ]]; then
     echo -e "(i) Restoring old settings...\n"
+
+    set_prop() { sed -i "s|$1=.*|$1=$2|g" $mod_path/data/settings.conf; }
 
     set_prop ver_logs $set_1
     set_prop auto_shut $set_2
@@ -343,8 +342,8 @@ else
 
   echo -e "(i) Setting permissions...\n"
 
-  set_perms_recursive $mod_path 0 0 644 755
-  set_perms_recursive $mod_path/system/bin 0 2000 755 755
+  set_perms_recursive $mod_path 0 0 0644 0755
+  set_perms_recursive $mod_path/system/bin 0 2000 0755 0755
 fi
 
 # Unmount the image
diff --git a/system/bin/mcc b/system/bin/mcc
--- a/system/bin/mcc
+++ b/system/bin/mcc
@@ -1,12 +1,12 @@
 #!/system/bin/sh
 # MC's Charging Controller (mcc)
 # mcc Main Script
-# versionCode = 201801011
+# versionCode = 201801021
 # MCMotherEffin' @ XDA Developers
 
 # Make sure mcc is running as root
 
-if ! (id | grep -iq uid=0); then
+if ! (id | grep -q uid=0); then
   su -c mcc $@; exit $?;
 else
   echo ' '
@@ -22,7 +22,7 @@ if [ ! "$no_logging" ]; then
 magisk_bb=$(find /data -type f -name busybox | grep /magisk/busybox$)
 
 if [ ! -x "$magisk_bb" ]; then
-  echo -e "(!) Could not find MAGISK internal BusyBox\n"
+  echo -e "(!) Could not find Magisk internal BusyBox\n"
   exit 1
 fi
 
@@ -38,7 +38,7 @@ else
   system=/system
 fi
 
-# Detect MAGISK mount point
+# Detect Magisk mount point
 
 for loop_device in /dev/block/loop*; do
 
@@ -60,7 +60,7 @@ done
 if [[ ! -z $mount_point ]]; then
   mod_dir=$mount_point/mcc
 else
-  echo -e "(!) Could not find MAGISK mount point\n"
+  echo -e "(!) Could not find Magisk mount point\n"
   exit 1
 fi
 
@@ -75,6 +75,14 @@ ver_log=$data_dir/verbose.log
 ## yields an error and exits 1
 
 error() { echo -e "(!) $1\n"; exit 1; }
+
+## logs a file content to the logfile
+
+log_file() {
+  echo -e "Filename :- $1\n\n" >>"$out_log"
+  cat $1 >>"$out_log"
+  echo -e "\n\n\n\n\n\n\n\n\n\n\n" >>"$out_log"
+}
 
 ## gets a property from a prop file
 
@@ -401,7 +409,7 @@ if ($(ver_logs)); then
       echo -e "(!) Verbose logs are enabled\n"
 
       getprop | grep product | tr -d [ | tr -d ] >$ver_log
-      echo -e "\nmcc_versionCode = 201801011\n" >>$ver_log
+      echo -e "\nmcc_versionCode = 201801021\n" >>$ver_log
       set -x 2>>$ver_log
     fi
   fi
@@ -487,15 +495,10 @@ case $1 in
     rm -f "$out_log"
     echo -e "(i) Gathering debugging data...\n"
 
-    echo -e "Filename :- /cache/mcc_init.log\n\n" >"$out_log"
-    cat /cache/mcc_init.log >>"$out_log"
-    echo -e "\n\n\n\n\n\n\n\n\n\n\n" >>"$out_log"
+    log_file /cache/mcc_init.log
     
     find $mod_dir -type f | while read entry; do
-
-      echo -e "Filename :- $entry\n\n" >>"$out_log"
-      cat $entry >>"$out_log"
-      echo -e "\n\n\n\n\n\n\n\n\n\n\n" >>"$out_log"
+      log_file $entry
     done
 
     echo -e "- Done\n"
@@ -566,7 +569,7 @@ case $1 in
   --disable) charge disable $2
       ;;
 
-## trigger service ( MAGISK )
+## trigger service ( Magisk )
 
   --service_trigger)
 
@@ -632,6 +635,7 @@ case $1 in
 
     if [[ ! -z $2 ]]; then
       test_level $2; test_level $1;
+
       if [[ $2 -gt $1 ]]; then
         test_diff $2 $1; test_update_udt $2 $1;
       else
